### ISSUE TITLE
actividad 5 - evelyn santiago victoria

### ISSUE THREAD

**Issue by EvelynSantiagoVic** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-EvelynSantiagoVic#1]
[actividad 5_tipos de textos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-EvelynSantiagoVic/files/9638111/actividad.5_tipos.de.textos.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion...

**Comment by Blanca-estela-valerio-rivero** [comment]
La calificación es 18 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
